apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - namespace.yaml
  - secrets.yaml
  - redis-deployment.yaml
  - deployment-oauth2-proxy.yaml
  - service-oauth2-proxy.yaml
  - ingress-oauth2-proxy.yaml
  - ingress.yaml
  - sample-app.yaml