apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-html
  namespace: app
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Authenticated App</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
                text-align: center;
            }
            .container {
                background: rgba(255, 255, 255, 0.1);
                padding: 40px;
                border-radius: 15px;
                box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
                backdrop-filter: blur(8px);
                border: 1px solid rgba(255, 255, 255, 0.18);
            }
            h1 {
                font-size: 2.5em;
                margin-bottom: 20px;
                text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
            }
            p {
                font-size: 1.2em;
                margin-bottom: 10px;
            }
            .auth-badge {
                background: #28a745;
                padding: 10px 20px;
                border-radius: 25px;
                display: inline-block;
                margin-top: 20px;
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🎉 Hello, I am authenticated from Auth0!</h1>
            <p>Welcome to the protected application</p>
            <p>You have successfully authenticated through OAuth2 Proxy</p>
            <div class="auth-badge">✅ Authenticated User</div>
        </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: custom-html
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: custom-html
          configMap:
            name: custom-html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example-service
  namespace: app
spec:
  selector:
    app: nginx-example
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
