apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: app
type: Opaque
data:
  client-id: REp0RWlwU1hLZ29VZHBFaHkwRENMMVdvVHlLSWtBbzM=
  client-secret: WGlXSXRqdEFiLWZYdGdiRHBScXpIWUZ6emVRVG4zcjdVUnZYZzFRamIzazVTN2xVTnB0SU5acEJVNXJGdHhQRA==
  cookie-secret: QjRqZWZNMUdmRnpGOHZNR0R1djZZZz09